---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "aws-secret"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${region}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa
            namespace: external-secrets
