---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: next-fe-app
  namespace: ${namespace}
spec:
  refreshInterval: 0h10m0s
  secretStoreRef:
    name: aws-secret
    kind: ClusterSecretStore
  target:
    name: next-fe-app
  dataFrom:
    - extract:
        key: ${project}/${namespace}/next-fe-app
