---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-next-fe-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com
    targetRevision: main
    path: kubernetes/next-fe-app
    helm:
      parameters:
        - name: "image.tag"
          value: "production"
      valueFiles:
        - values-production.yaml
             
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
